import type { StageSlug } from './stages';

export type CapabilityStatus = 'available' | 'scope-check-required';

export interface ProductCapability {
  capabilityId: string;
  name: string;
  category: 'ai' | 'course' | 'practice' | 'primary' | 'junior' | 'service';
  status: CapabilityStatus;
  stageScopes: StageSlug[];
  solves: string;
  usage: string;
  frequency: string;
  acceptance: string;
  boundary: string;
  consultantSummary: string;
  sourceRefs: string[];
  verifiedAt: string;
}

const ALL_STAGES: StageSlug[] = ['elementary', 'middle', 'high'];
const VERIFIED_AT = '2026-09-06';

export const PRODUCT_CAPABILITIES: ProductCapability[] = [
  {
    capabilityId: 'CAP-AI-01',
    name: 'AI拍题精学',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '遇到题只找答案，不知道题目考什么，也不知道该补哪个知识点',
    usage: '拍题识别考点，查看思路，学习对应微课，再做同类或变式题',
    frequency: '遇到代表性错题时使用，不把每道题都交给工具',
    acceptance: '脱离答案后能说出考点和第一步，24至48小时后换题仍能起步',
    boundary: '具体题目、设备和学科覆盖使用前核实，不能替代独立思考',
    consultantSummary: '不是帮孩子搜答案，而是把题拆回真正没懂的知识点',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-AI-02',
    name: 'AI错题本',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '错题只改答案、不归因，换个问法继续错',
    usage: '收录错题，标注概念、计算、审题、步骤或方法错因，关联知识点后延迟复测',
    frequency: '当天收录，每周集中复盘一次，每次追一至两类高频错因',
    acceptance: '同类错误下降，孩子能说清错在哪里和下次先检查什么',
    boundary: '录入不等于掌握，必须重新作答并延迟复测',
    consultantSummary: '错题本不是存得多，而是让孩子知道为什么总在同一处丢分',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-AI-03',
    name: 'AI定制班',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '不知道每天学什么，多科任务冲突，目标无法落到当天',
    usage: '录入当前水平和目标，生成每日任务，完成后依据反馈调整后续内容',
    frequency: '按日执行，每周查看完成率和正确率并调整',
    acceptance: '任务完成率稳定，薄弱点减少，作业和自主学习时间可控',
    boundary: '班型、覆盖年级和具体权益以当期产品为准，不承诺自动提分',
    consultantSummary: '把大目标拆成孩子今天该完成的那一小块',
    sourceRefs: ['SRC-PRODUCT-02'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-AI-04',
    name: '课中答疑',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '看课时某一步没听懂，卡住后退出或带着疑问继续',
    usage: '围绕当前步骤提出具体问题，获得解释后回到原步骤并用一道题验证',
    frequency: '只在明确卡点时使用',
    acceptance: '能用自己的话复述卡点，并完成紧随其后的练习',
    boundary: '具体课程范围和入口使用前核实',
    consultantSummary: '孩子卡在哪一步，就在那一步把问题问清楚',
    sourceRefs: ['SRC-PRODUCT-01'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-AI-05',
    name: '极速预习',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '课堂节奏快，第一次接触新概念时来不及理解',
    usage: '课前短时认识关键词和基本关系，标记一个疑问，第二天带着问题听课',
    frequency: '新课前10至15分钟，不提前学完整章',
    acceptance: '能说出课程主题和两至三个关键词，课后能说明疑问是否解决',
    boundary: '具体学段和学科覆盖使用前核实，不能替代学校课堂',
    consultantSummary: '预习先混个脸熟，让第二天课堂不再全程被动',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-AI-06',
    name: '极速复习',
    category: 'ai',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '当天没听懂却没有及时补，漏洞积累到周末或考试前',
    usage: '当天定位未懂环节，快速回看核心内容，做两至三道基础验证题',
    frequency: '当天或次日，每次10至20分钟',
    acceptance: '基础题正确率约80%，并能说出规则或方法',
    boundary: '具体学段和学科覆盖使用前核实',
    consultantSummary: '当天的小漏洞当天补，成本最低',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-COURSE-01',
    name: '同步概念课',
    category: 'course',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '学校正在学的概念没听懂，记住结论却不知道为什么',
    usage: '按教材和章节选择约5至8分钟的知识点微课，完成随堂练习后口头复述',
    frequency: '按当前真实进度，在课堂前后处理一个最小知识点',
    acceptance: '能解释概念、判断典型正误并完成基础应用',
    boundary: '具体时长、教材版本和覆盖范围以当期产品页面为准',
    consultantSummary: '先把学校当天那一个小概念拆开讲清楚，再去做题',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-COURSE-02',
    name: '同步解题课',
    category: 'course',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '概念听懂了，但题目一变就不会，不知道什么时候用哪个方法',
    usage: '学习题型条件和起手步骤，模仿一题，再独立完成两至三道变式题',
    frequency: '概念通过基础验证后使用',
    acceptance: '新题能独立判断题型并完成第一步，同类变式正确率稳定',
    boundary: '不能用解题课掩盖尚未补清的概念断点',
    consultantSummary: '概念课解决听懂，解题课解决怎么用',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-COURSE-03',
    name: '培优课',
    category: 'course',
    status: 'scope-check-required',
    stageScopes: ALL_STAGES,
    solves: '基础和中档题较稳，但高阶模型、综合迁移和拔高题缺少方法',
    usage: '确认前置知识达标后学习高阶模型，完成典型题并复盘适用条件',
    frequency: '基础与中档题稳定后按模块安排',
    acceptance: '能识别同类模型并解释适用条件，而非只会一道难题',
    boundary: '基础未稳时不应优先使用，具体适用范围需核实',
    consultantSummary: '培优不是先上难题，而是基础稳后再补高阶方法',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-COURSE-04',
    name: '总复习课',
    category: 'course',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '知识零散，进入期中、期末或升学复习后无从下手',
    usage: '按模块回顾并做诊断题，把错题定位回知识点后针对性补课与练习',
    frequency: '学期复习或毕业年级复习节点使用',
    acceptance: '能说出模块关系，综合卷基础与中档题更稳定',
    boundary: '不是从第一页平均重学，必须服从当前考试范围',
    consultantSummary: '先用题把漏洞照出来，只补真正断掉的地方',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRACTICE-01',
    name: '同步刷题',
    category: 'practice',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '新课学完缺少及时验证',
    usage: '学完当前知识点后做少量同层练习，再判断错因',
    frequency: '每个知识点学习后短练',
    acceptance: '基础题正确率稳定且能说出依据',
    boundary: '概念没懂或抵触明显时先降门槛，不用题量掩盖问题',
    consultantSummary: '学完马上用少量题确认，不靠刷很多制造安心感',
    sourceRefs: ['SRC-PRODUCT-01'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRACTICE-03',
    name: '作业题型速攻',
    category: 'practice',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '作业不会起步，同类题耗时过长',
    usage: '围绕当天作业的高频卡题学习起手步骤并短练',
    frequency: '发现同类题连续卡住时使用',
    acceptance: '独立起步率提高，同类作业耗时下降',
    boundary: '先统计真实卡点和耗时，不能把催快当成解决方案',
    consultantSummary: '先解决最耗时间的那类题，让作业节奏恢复',
    sourceRefs: ['SRC-PRODUCT-01'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRACTICE-04',
    name: '专项突破',
    category: 'practice',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '一个题型或能力长期拖分',
    usage: '锁定最小专项连续练习，并用延迟复测确认稳定性',
    frequency: '一周只追一至两个高价值漏洞',
    acceptance: '专项正确率和稳定性达标',
    boundary: '不得超出学校当前进度或考试范围',
    consultantSummary: '一周只追一个关键漏洞，练完必须换题复测',
    sourceRefs: ['SRC-PRODUCT-01'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRACTICE-06',
    name: '试卷库',
    category: 'practice',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '需要整卷诊断、限时训练或考后复盘',
    usage: '确认考试范围后选卷，限时完成，再按模块统计失分结构',
    frequency: '阶段考试前后使用，不日常高频整卷',
    acceptance: '能识别失分结构，而不是只看总分',
    boundary: '范围未确认时不使用整卷推断具体知识点',
    consultantSummary: '试卷不是为了再考一次，而是看分到底丢在哪一类题',
    sourceRefs: ['SRC-PRODUCT-01'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRIMARY-01',
    name: '计算题专题',
    category: 'primary',
    status: 'available',
    stageScopes: ['elementary'],
    solves: '口算慢、竖式错、符号和进退位不稳',
    usage: '先区分规则、书写和注意力错误，再做短时定量训练与复盘',
    frequency: '每天10至15分钟',
    acceptance: '正确率、速度和书写过程同步改善',
    boundary: '不把所有计算错误都归因于粗心',
    consultantSummary: '先分清是哪一种计算错误，再做短练',
    sourceRefs: ['SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-PRIMARY-02',
    name: '应用题专题',
    category: 'primary',
    status: 'available',
    stageScopes: ['elementary'],
    solves: '题目读得懂但列不出式，数量关系混乱',
    usage: '圈条件和问题，画图或说数量关系，再列式并检查单位',
    frequency: '每次一至两题，重在口述过程',
    acceptance: '能说清已知、所求、先算什么以及为什么',
    boundary: '不能只对答案，也不能由家长直接代列算式',
    consultantSummary: '让孩子把题目关系说出来，再动笔列式',
    sourceRefs: ['SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-JUNIOR-01',
    name: '初中词汇训练',
    category: 'junior',
    status: 'available',
    stageScopes: ['middle'],
    solves: '单词背过又忘，阅读中识别慢',
    usage: '音形义结合，在句子中识别并做间隔复习',
    frequency: '每天短时输入，每周复测',
    acceptance: '能在句子和阅读中快速识别，而非只会中英互译',
    boundary: '不能替代长难句、阅读方法和写作输出',
    consultantSummary: '背单词不只背中文意思，还要在句子里认得出来',
    sourceRefs: ['SRC-PRODUCT-03'],
    verifiedAt: VERIFIED_AT,
  },
  {
    capabilityId: 'CAP-SERVICE-01',
    name: '学习数据与反馈',
    category: 'service',
    status: 'available',
    stageScopes: ALL_STAGES,
    solves: '家长只看到孩子坐着学，不知道学了什么、哪里不会、是否有效',
    usage: '查看完成、正确率和薄弱点，每周只确定一个优先问题并调整任务',
    frequency: '每周一次集中复盘',
    acceptance: '家长关注结果而非盯时长，孩子知道下周具体改什么',
    boundary: '数据必须结合真实作业和学校考试，不单独下结论',
    consultantSummary: '家长不用天天盯，按周看孩子到底解决了哪个问题',
    sourceRefs: ['SRC-PRODUCT-01', 'SRC-PRODUCT-02'],
    verifiedAt: VERIFIED_AT,
  },
];

export function getProductCapabilities(
  capabilityIds: string[],
  stage: StageSlug,
): ProductCapability[] {
  const uniqueIds = new Set(capabilityIds);
  return PRODUCT_CAPABILITIES.filter((capability) => (
    uniqueIds.has(capability.capabilityId) && capability.stageScopes.includes(stage)
  ));
}
